// Starter editorial calendar, importable in one click from /admin/blog/planning. "When to go /
// which to choose" guides — high-demand searches for destinations the site sells trips to.
export const DEFAULT_BLOG_TOPICS: { slug: string; title: string }[] = [
  { slug: "quand-partir-en-tanzanie", title: "Quand partir en Tanzanie : safari, Kilimandjaro et Zanzibar" },
  { slug: "quand-partir-au-perou", title: "Quand partir au Pérou : Machu Picchu et saison sèche" },
  { slug: "quand-partir-en-thailande", title: "Quand partir en Thaïlande : le guide région par région" },
  { slug: "quand-partir-au-vietnam", title: "Quand partir au Vietnam : nord, centre et sud" },
  { slug: "premier-safari-quel-pays-choisir", title: "Premier safari : Kenya, Tanzanie, Botswana ou Afrique du Sud ?" },
  { slug: "quand-partir-en-afrique-du-sud", title: "Quand partir en Afrique du Sud : safari, Cap et route des jardins" },
  { slug: "quand-partir-au-costa-rica", title: "Quand partir au Costa Rica : saison sèche et saison verte" },
  { slug: "quand-partir-aux-maldives", title: "Quand partir aux Maldives : moussons et meilleurs mois" },
  { slug: "quand-partir-en-jordanie", title: "Quand partir en Jordanie : Petra, Wadi Rum et mer Morte" },
  { slug: "quand-partir-en-egypte", title: "Quand partir en Égypte : croisière sur le Nil et mer Rouge" },
  { slug: "quand-partir-au-sri-lanka", title: "Quand partir au Sri Lanka : les deux moussons expliquées" },
  { slug: "quand-partir-a-bali", title: "Quand partir à Bali et en Indonésie" },
  { slug: "quand-partir-en-namibie", title: "Quand partir en Namibie : désert, Etosha et côte" },
  { slug: "quand-partir-en-nouvelle-zelande", title: "Quand partir en Nouvelle-Zélande : île du Nord et du Sud" },
  { slug: "desert-maroc-agafay-merzouga-erg-chigaga", title: "Désert au Maroc : Agafay, Merzouga ou Erg Chigaga ?" },
  { slug: "quand-partir-en-argentine", title: "Quand partir en Argentine : Patagonie, Iguazú et Buenos Aires" },
  { slug: "quand-partir-au-mexique", title: "Quand partir au Mexique : Yucatán, Oaxaca et côte Pacifique" },
  { slug: "quand-partir-en-inde", title: "Quand partir en Inde : Rajasthan, Kerala et Himalaya" },
  { slug: "quand-partir-a-l-ile-maurice", title: "Quand partir à l'île Maurice : climat et meilleurs mois" },
  { slug: "voir-les-gorilles-rwanda-ouganda", title: "Voir les gorilles : Rwanda ou Ouganda ?" },
  { slug: "quand-partir-au-canada", title: "Quand partir au Canada : été, automne indien et hiver" },
  { slug: "quand-partir-au-botswana", title: "Quand partir au Botswana : delta de l'Okavango et Chobe" },
  { slug: "quand-partir-a-madagascar", title: "Quand partir à Madagascar : saison sèche et baleines" },
  { slug: "quand-partir-au-chili", title: "Quand partir au Chili : Atacama, Patagonie et île de Pâques" },
  { slug: "quand-partir-en-colombie", title: "Quand partir en Colombie : Carthagène, café et Caraïbes" },
  { slug: "voyage-en-famille-destinations-selon-age", title: "Voyage en famille : quelle destination selon l'âge des enfants ?" },
  { slug: "quand-partir-en-norvege", title: "Quand partir en Norvège : fjords, soleil de minuit et aurores" },
  { slug: "quand-partir-au-portugal", title: "Quand partir au Portugal : Lisbonne, Porto, Algarve et Açores" },
  { slug: "quand-partir-en-turquie", title: "Quand partir en Turquie : Istanbul, Cappadoce et côte égéenne" },
  { slug: "quand-partir-en-polynesie-francaise", title: "Quand partir en Polynésie française : saison sèche et baleines" },
];
