import { PrismaClient } from "@prisma/client";

const db = new PrismaClient();

const tours = [
  {
    name: "Agadir City Tour et Cable Car",
    nameEn: "Agadir City Tour & Cable Car Ride",
    nameEs: "Tour por Agadir y teleférico",
    slug: "agadir-city-tour-cable-car",
    tagline: "Médina, Kasbah et vue panoramique sur la baie",
    taglineEn: "Medina, Kasbah and a panoramic view over the bay",
    taglineEs: "Medina, Kasbah y vista panorámica de la bahía",
    price: 50,
    originalPrice: 65,
    duration: "1 jour",
    durationEn: "1 day",
    durationEs: "1 día",
    category: "activity",
    theme: "culture",
    featured: true,
    order: 1,
  },
  {
    name: "Agadir Quad Adventure",
    nameEn: "Agadir Quad Adventure Experience",
    nameEs: "Aventura en quad en Agadir",
    slug: "agadir-quad-adventure",
    tagline: "Dunes et pistes du Souss-Massa en quad",
    taglineEn: "Dunes and trails of Souss-Massa by quad bike",
    taglineEs: "Dunas y pistas de Souss-Massa en quad",
    price: 45,
    originalPrice: 50,
    duration: "1 jour",
    durationEn: "1 day",
    durationEs: "1 día",
    category: "activity",
    theme: "adventure",
    featured: true,
    order: 2,
  },
  {
    name: "Balade à dos de chameau avec barbecue",
    nameEn: "Camel Ride with Barbecue",
    nameEs: "Paseo en camello con barbacoa",
    slug: "camel-ride-barbecue",
    tagline: "Coucher de soleil sur la plage, à dos de chameau",
    taglineEn: "Sunset on the beach, from the back of a camel",
    taglineEs: "Atardecer en la playa, a lomos de camello",
    price: 40,
    originalPrice: 45,
    duration: "2 heures",
    durationEn: "2 hours",
    durationEs: "2 horas",
    category: "activity",
    theme: "family",
    featured: false,
    order: 3,
  },
  {
    name: "Hammam et Massage",
    nameEn: "Massage & Hammam Experience",
    nameEs: "Experiencia de hammam y masaje",
    slug: "hammam-massage",
    tagline: "Rituel traditionnel marocain, gommage et massage",
    taglineEn: "Traditional Moroccan ritual, scrub and massage",
    taglineEs: "Ritual tradicional marroquí, exfoliación y masaje",
    price: 45,
    originalPrice: 50,
    duration: "1 jour",
    durationEn: "1 day",
    durationEs: "1 día",
    category: "activity",
    theme: "relax",
    featured: true,
    order: 4,
  },
  {
    name: "Cours de cuisine berbère",
    nameEn: "Berber Cooking Class",
    nameEs: "Clase de cocina bereber",
    slug: "cours-cuisine-berbere",
    tagline: "4h en cuisine avec une famille locale",
    taglineEn: "4 hours in the kitchen with a local family",
    taglineEs: "4 horas de cocina con una familia local",
    price: 56,
    originalPrice: 70,
    duration: "4 heures",
    durationEn: "4 hours",
    durationEs: "4 horas",
    category: "activity",
    theme: "culture",
    featured: false,
    order: 5,
  },
  {
    name: "Excursion à Tafraout",
    nameEn: "Day Trip to Tafraout",
    nameEs: "Excursión de un día a Tafraout",
    slug: "excursion-tafraout",
    tagline: "Vallées d'amandiers et rochers peints de l'Anti-Atlas",
    taglineEn: "Almond valleys and painted rocks of the Anti-Atlas",
    taglineEs: "Valles de almendros y rocas pintadas del Anti-Atlas",
    price: 75,
    originalPrice: 85,
    duration: "1 jour",
    durationEn: "1 day",
    durationEs: "1 día",
    category: "tour",
    theme: "culture",
    featured: false,
    order: 6,
  },
  {
    name: "Paradise Valley",
    nameEn: "Agadir Paradise Valley Tour",
    nameEs: "Tour por Paradise Valley",
    slug: "paradise-valley",
    tagline: "Piscines naturelles nichées dans la vallée de l'Atlas",
    taglineEn: "Natural pools tucked into the Atlas valley",
    taglineEs: "Piscinas naturales en el valle del Atlas",
    price: 25,
    originalPrice: 45,
    duration: "1 jour",
    durationEn: "1 day",
    durationEs: "1 día",
    category: "tour",
    theme: "family",
    featured: true,
    order: 7,
  },
  {
    name: "Découverte de Taghazout",
    nameEn: "Taghazout Town Discovery",
    nameEs: "Descubrimiento de Taghazout",
    slug: "decouverte-taghazout",
    tagline: "Village de surfeurs et plages sauvages",
    taglineEn: "Surfers' village and wild beaches",
    taglineEs: "Pueblo de surfistas y playas salvajes",
    price: 35,
    originalPrice: 45,
    duration: "1 jour",
    durationEn: "1 day",
    durationEs: "1 día",
    category: "tour",
    theme: "relax",
    featured: false,
    order: 8,
  },
  {
    name: "Marrakech au départ d'Agadir",
    nameEn: "Marrakech Trip from Agadir",
    nameEs: "Viaje a Marrakech desde Agadir",
    slug: "marrakech-depuis-agadir",
    tagline: "La ville rouge en une journée",
    taglineEn: "The Red City in a single day",
    taglineEs: "La ciudad roja en un día",
    price: 45,
    originalPrice: 53,
    duration: "1 jour",
    durationEn: "1 day",
    durationEs: "1 día",
    category: "tour",
    theme: "culture",
    featured: false,
    order: 9,
  },
  {
    name: "Safari désert avec déjeuner",
    nameEn: "Agadir Desert Safari with Lunch",
    nameEs: "Safari por el desierto con almuerzo",
    slug: "safari-desert-dejeuner",
    tagline: "Sidi R'bat, dunes et déjeuner traditionnel",
    taglineEn: "Sidi R'bat, dunes and a traditional lunch",
    taglineEs: "Sidi R'bat, dunas y almuerzo tradicional",
    price: 55,
    originalPrice: 56,
    duration: "1 jour",
    durationEn: "1 day",
    durationEs: "1 día",
    category: "tour",
    theme: "adventure",
    featured: true,
    order: 10,
  },
  {
    name: "Parc National de Souss-Massa en 4x4",
    nameEn: "Souss Massa National Park 4x4",
    nameEs: "Parque Nacional Souss-Massa en 4x4",
    slug: "souss-massa-4x4",
    tagline: "Faune protégée et paysages sauvages",
    taglineEn: "Protected wildlife and wild landscapes",
    taglineEs: "Fauna protegida y paisajes salvajes",
    price: 96,
    originalPrice: 96,
    duration: "1 jour",
    durationEn: "1 day",
    durationEs: "1 día",
    category: "tour",
    theme: "adventure",
    featured: false,
    order: 11,
  },
  {
    name: "Circuit désert de Merzouga — 3 jours",
    nameEn: "3-Day Merzouga Desert Tour",
    nameEs: "Circuito de 3 días por el desierto de Merzouga",
    slug: "merzouga-3-jours",
    tagline: "Nuit sous les étoiles dans le grand Sahara",
    taglineEn: "A night under the stars in the great Sahara",
    taglineEs: "Una noche bajo las estrellas en el gran Sahara",
    price: 450,
    originalPrice: 500,
    duration: "3 jours",
    durationEn: "3 days",
    durationEs: "3 días",
    category: "multi-day",
    theme: "adventure",
    featured: true,
    order: 12,
  },
];

async function main() {
  for (const tour of tours) {
    await db.tour.upsert({
      where: { slug: tour.slug },
      update: tour,
      create: { ...tour, currency: "EUR", departureFrom: "Agadir" },
    });
  }
  console.log(`Seeded ${tours.length} tours.`);
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => db.$disconnect());
